[settings]
lockfile = true

[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"

[tools]
checkov = "3.3.2"
fnox = "1.19.0"
infracost = "0.10.42"
terraform = "1.13.1"
terraform-docs = "0.16.0"
terraform-ls = "0.38.2"
terragrunt = "0.86.2"
tflint = "0.58.1"
tfupdate = "0.8.5"
trivy = "0.71.2"

[env]
_.fnox-env = { tools = true }
ROOT_DIR = { value = "{{ config_root }}", path = true }
PASSWORD_STORE_DIR = { value = "{{ config_root }}/../password-store", path = true }
SECRETS = { value = "{{ config_root }}/.secrets", path = true }
TF_CLI_CONFIG_FILE = { value = "{{ config_root }}/.terraformrc", path = true }
TF_LOG = ""
TG_PROVIDER_CACHE = 1
TG_PROVIDER_CACHE_DIR = "{{ config_root }}/.terragrunt-cache/terragrunt/providers"
TG_NO_AUTO_INIT = 0
TG_NON_INTERACTIVE = 0
TG_QUEUE_EXCLUDE_EXTERNAL = 1
KUBECONFIG="{{ env.SECRETS }}/tools.kubeconfig:{{ env.SECRETS }}/dev.kubeconfig:{{ env.SECRETS }}/prod.kubeconfig"

[tool_alias]
checkov = "pipx:checkov"
trivy = "aqua:trivy"
