#!/usr/bin/env bash
#MISE description="retrieve argocd initial-admin-password post installation"
#MISE dir="{{cwd}}"

echo "[INFO] your kubeconfig is ${KUBECONFIG:-$HOME/.kube/config}" >&2
echo "[INFO] your context is $(kubectl config current-context)" >&2

kubectl -n argocd get secret argocd-initial-admin-secret -o json | jq -r '.data.password' | base64 -d
